language: java

dist: xenial

if: |
  repo != jenkinsci/gitlab-branch-source-plugin OR \
  type = pull_request OR \
  branch = master

before_cache:
  - rm -rf $HOME/.m2/repository/io/jenkins/plugins/gitlab-branch-source*

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - JAVA_LEVEL=8

matrix:
  include:
    - jdk: openjdk11
      env:
        - MVN_FLAG='-Daccess-modifier-checker.failOnError=true'
    - jdk: openjdk8

install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V $MVN_FLAG -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

script:
  - |
    mvn clean install -B \
      -Djava.level=$JAVA_LEVEL \
      $MVN_FLAG -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

notifications:
  email: false
